"""Genetic algorithm for MRF labeling with a genuinely discrete chromosome.

Unlike `solve_sa_discrete.solve_sa` (one state annealed over time), GA keeps
a whole *population* of candidate label maps per batch item and evolves it
generation by generation. The chromosome is the label map itself — one gene
per voxel, allele = a label in [0, L) — so, exactly as in the SA/greedy
solvers, every individual ever produced is already a valid one-label-per-
voxel assignment; there is no continuous relaxation or repair step.

Algorithm sketch, standard generational GA:
    0. init:      `pop_size` individuals per batch item, generated by
                   randomly mutating copies of the unary-greedy seed
                   labeling (diverse population, centered on a good start).
    1. evaluate:  fitness of every individual = `total_cost` (lower is
                   better; selection below is cost-minimizing).
    2. selection: for each of `pop_size` offspring slots, run tournament
                   selection twice (parent A, parent B) — draw
                   `tournament_size` individuals uniformly at random and
                   keep the cheapest, biasing reproduction toward fitter
                   individuals without computing a full fitness-
                   proportionate distribution.
    3. crossover: per-voxel uniform crossover — every voxel independently
                   inherits its label from parent A or parent B with equal
                   probability. Since both parents are already valid
                   labelings, the child is automatically valid too.
    4. mutation:  per-voxel random-reset mutation — with probability
                   `p_mutation`, replace a voxel's inherited label with one
                   drawn uniformly from the L-1 other labels (same proposal
                   distribution as `solve_sa_discrete._propose_labels`).
    5. elitism:   the `n_elite` cheapest individuals of the current
                   generation survive unchanged into the next, replacing
                   the `n_elite` most expensive offspring — guarantees the
                   best-found cost never gets worse across generations.
    6. repeat steps 1-5 for `n_generations`; return the best individual
                   ever seen.

Population and batch are fused into one leading dimension whenever data is
handed to `objective.total_cost` (which only assumes a leading batch dim),
and reshaped back to (N, P, ...) for population-level operators (selection,
crossover, elitism) — every operator below is a batched tensor op with no
Python loop over individuals or generations' internals.
"""

import torch
import torch.nn.functional as F
from torch import Tensor
from typing import Optional, Callable

from post_process.objective import total_cost, total_enclosure_cost
from post_process.solve_sa_discrete import _propose_labels


def _population_cost(
    C_unary: Tensor,
    C_adj: Tensor,
    labels: Tensor,
    forbidden_enclosure_pairs: Optional[list[tuple[int, int]]] = None,
    C_enclose: float = 1e6,
) -> Tensor:
    """Cost of every individual in the population.

    :param C_unary: (N, W, H, D, L)
    :param C_adj:   (L, L)
    :param labels:  (N, P, W, H, D) int64
    :param forbidden_enclosure_pairs: list of (inner_layer_id, outer_layer_id)
                     pairs that must not fully enclose one another; see
                     `objective.enclosure_cost`. None disables the term.
    :param C_enclose: penalty weight applied per forbidden-enclosure violation
    :return:        (N, P) cost of each individual
    """
    N, P, W, H, D = labels.shape
    L = C_unary.shape[-1]

    C_unary_pop = C_unary.unsqueeze(1).expand(N, P, W, H, D, L).reshape(N * P, W, H, D, L)
    labels_pop = labels.reshape(N * P, W, H, D)
    X_pop = F.one_hot(labels_pop, L).to(C_unary.dtype)

    cost = total_cost(C_unary_pop, X_pop, C_adj)  # (N*P, 1)
    if forbidden_enclosure_pairs:
        cost = cost + total_enclosure_cost(labels_pop, forbidden_enclosure_pairs, C_enclose)
    return cost.reshape(N, P)


def _tournament_select(cost: Tensor, k: int, n_select: int, generator: Optional[torch.Generator]) -> Tensor:
    """Tournament selection: pick `n_select` parent indices per batch item.

    For each of the `n_select` slots, draw `k` candidates uniformly at
    random (with replacement) from the population and keep the one with
    lowest cost.

    :param cost: (N, P)
    :return:     (N, n_select) int64, indices into the population dim
    """
    N, P = cost.shape
    device = cost.device

    candidates = torch.randint(0, P, (N, n_select * k), device=device, generator=generator)  # (N, n_select*k)
    candidate_cost = cost.gather(1, candidates).view(N, n_select, k)
    candidates = candidates.view(N, n_select, k)

    winner = candidate_cost.argmin(dim=-1, keepdim=True)  # (N, n_select, 1)
    return candidates.gather(-1, winner).squeeze(-1)  # (N, n_select)


def _gather_population(labels: Tensor, idx: Tensor) -> Tensor:
    """Gather individuals out of a population by index.

    :param labels: (N, P, W, H, D)
    :param idx:    (N, M) indices into the P dim
    :return:       (N, M, W, H, D)
    """
    N, P, W, H, D = labels.shape
    M = idx.shape[1]
    idx = idx.view(N, M, 1, 1, 1).expand(N, M, W, H, D)
    return labels.gather(1, idx)


def solve_ga(
    C_unary: Tensor,
    C_adj: Tensor,
    X_init: Optional[Tensor] = None,
    *,
    forbidden_enclosure_pairs: Optional[list[tuple[int, int]]] = None,
    C_enclose: float = 1e6,
    pop_size: int = 32,
    n_generations: int = 200,
    tournament_size: int = 3,
    p_mutation: float = 0.02,
    n_elite: int = 2,
    init_mutation_rate: float = 0.1,
    generator: Optional[torch.Generator] = None,
    validate_fn: Callable = None,
    verbose: bool = True,
) -> Tensor:
    """
    Genetic algorithm for MRF labeling, evolving a population of integer
    label maps directly (no continuous relaxation).

    Chromosome:  a full label map `labels` of shape (W, H, D), one gene per
                 voxel, allele = label in [0, L).
    Population:  `pop_size` chromosomes per batch item, shape (N, P, W, H, D).
    Fitness:     `total_cost` (selection below minimizes cost).

    See module docstring for the generational loop (selection -> uniform
    crossover -> random-reset mutation -> elitism).

    :param C_unary:   (N, W, H, D, L) per-voxel-per-label unary costs
    :param C_adj:     (L, L) pairwise adjacency cost matrix
    :param X_init:    optional warm-start logits/one-hot (N, W, H, D, L);
                       defaults to the per-voxel unary-greedy labeling
                       (argmin over C_unary). The initial population is
                       generated by randomly mutating copies of this seed,
                       so it starts diverse but centered on a good solution.
    :param forbidden_enclosure_pairs: list of (inner_layer_id, outer_layer_id)
                       pairs that must not fully enclose one another; see
                       `objective.enclosure_cost`. None disables the term.
    :param C_enclose: penalty weight applied per forbidden-enclosure violation
    :param pop_size:  number of individuals per batch item
    :param n_generations: number of generations to run
    :param tournament_size: number of candidates per tournament-selection draw
    :param p_mutation: per-voxel probability of random-reset mutation
    :param n_elite:    number of top individuals carried over unchanged each generation
    :param init_mutation_rate: per-voxel mutation probability used only to
                       diversify the initial population around the seed labeling
    :param generator:  torch Generator for reproducibility
    :param validate_fn: optional callback(labels) -> printed each generation when verbose
    :param verbose:    print progress per generation
    :return:           (N, W, H, D, L) one-hot label assignment
    """
    device = C_unary.device
    orig_dtype = C_unary.dtype
    N, W, H, D, L = C_unary.shape
    P = pop_size

    seed = (
        C_unary.argmin(dim=-1) if X_init is None else X_init.argmax(dim=-1)
    ).to(torch.int64)  # (N, W, H, D)

    C_adj = C_adj.to(dtype=orig_dtype, device=device)

    # Initial population: pop_size independently-mutated copies of the seed.
    labels = seed.unsqueeze(1).expand(N, P, W, H, D).clone()  # (N, P, W, H, D)
    init_mutate = torch.rand(labels.shape, device=device, generator=generator) < init_mutation_rate
    labels = torch.where(init_mutate, _propose_labels(labels, L, generator), labels)

    cost = _population_cost(C_unary, C_adj, labels, forbidden_enclosure_pairs, C_enclose)  # (N, P)
    best_idx = cost.argmin(dim=1, keepdim=True)  # (N, 1)
    best = {
        'gen': 0,
        'labels': _gather_population(labels, best_idx).squeeze(1),  # (N, W, H, D)
        'cost': cost.gather(1, best_idx),  # (N, 1)
    }

    for gen in range(n_generations):
        parent1_idx = _tournament_select(cost, tournament_size, P, generator)  # (N, P)
        parent2_idx = _tournament_select(cost, tournament_size, P, generator)  # (N, P)
        parent1 = _gather_population(labels, parent1_idx)  # (N, P, W, H, D)
        parent2 = _gather_population(labels, parent2_idx)  # (N, P, W, H, D)

        crossover_mask = torch.rand(parent1.shape, device=device, generator=generator) < 0.5
        offspring = torch.where(crossover_mask, parent1, parent2)  # (N, P, W, H, D)

        mutate_mask = torch.rand(offspring.shape, device=device, generator=generator) < p_mutation
        offspring = torch.where(mutate_mask, _propose_labels(offspring, L, generator), offspring)

        offspring_cost = _population_cost(C_unary, C_adj, offspring, forbidden_enclosure_pairs, C_enclose)  # (N, P)

        if n_elite > 0:
            elite_idx = cost.argsort(dim=1)[:, :n_elite]  # (N, n_elite), cheapest first
            elites = _gather_population(labels, elite_idx)  # (N, n_elite, W, H, D)
            elite_cost = cost.gather(1, elite_idx)  # (N, n_elite)

            worst_idx = offspring_cost.argsort(dim=1, descending=True)[:, :n_elite]  # (N, n_elite)
            scatter_idx = worst_idx.view(N, n_elite, 1, 1, 1).expand(N, n_elite, W, H, D)
            offspring.scatter_(1, scatter_idx, elites)
            offspring_cost.scatter_(1, worst_idx, elite_cost)

        labels = offspring
        cost = offspring_cost

        gen_best_idx = cost.argmin(dim=1, keepdim=True)  # (N, 1)
        gen_best_cost = cost.gather(1, gen_best_idx)  # (N, 1)
        improved = gen_best_cost < best['cost']  # (N, 1)
        if improved.any():
            gen_best_labels = _gather_population(labels, gen_best_idx).squeeze(1)
            improved_mask = improved.view(N, 1, 1, 1)
            best['labels'] = torch.where(improved_mask, gen_best_labels, best['labels'])
            best['cost'] = torch.where(improved, gen_best_cost, best['cost'])
            best['gen'] = gen

        if verbose:
            if validate_fn is not None:
                valid_result = validate_fn(best['labels'])
                print(f"Gen {gen} | Best Cost: {best['cost'].mean():.4f} | Pop Mean Cost: {cost.mean():.4f} | Valid Result: {valid_result}")
            else:
                print(f"Gen {gen} | Best Cost: {best['cost'].mean():.4f} | Pop Mean Cost: {cost.mean():.4f}")

    if verbose:
        print(f"Best Gen: {best['gen']} | Cost: {best['cost']}")

    return F.one_hot(best['labels'], L).to(orig_dtype)