"""Particle swarm optimization for MRF labeling over continuous (logit) variables.

Companion to `solve_sa_continuous.solve_sa`: same relaxation (optimize a
continuous logit tensor X of shape (N, W, H, D, L), discretize via argmax at
every evaluation), but instead of annealing a single state, PSO evolves a
whole *swarm* of `n_particles` candidate logit tensors per batch item,
exactly as `solve_ga_discrete.solve_ga` evolves a population of discrete
label maps. Population and batch are fused into one leading dimension
whenever data is handed to `objective.total_cost`, and reshaped back to
(N, P, ...) for swarm-level bookkeeping — no Python loop over particles.

Algorithm sketch, standard synchronous global-best PSO:
    0. init:      `n_particles` positions per batch item, generated by
                   perturbing the unary-greedy seed (`X_init` or -C_unary)
                   with Gaussian noise (one particle keeps the unperturbed
                   seed, mirroring GA's elitist-seeded population). Initial
                   velocities are small uniform noise.
    1. evaluate:  fitness of every particle = `total_cost` of its
                   hard-assigned (argmax) labeling.
    2. pbest:     each particle remembers the best position it has
                   personally visited.
    3. gbest:     each batch item shares one global-best position, the best
                   pbest across its own particles only (batch items never
                   share information with each other).
    4. velocity:  v <- w*v + c1*r1*(pbest - x) + c2*r2*(gbest - x), with
                   r1, r2 fresh per-element U(0,1) draws and w linearly
                   annealed from `w_init` to `w_final` — standard inertia-
                   weight PSO, trading exploration (high w, early) for
                   exploitation (low w, late).
    5. position:  x <- x + v (velocity optionally clamped to +/- v_max).
    6. repeat steps 1-5 for `n_iter`; return the best pbest ever seen,
                   hard-assigned.
"""

import torch
from torch import Tensor
from typing import Optional, Callable

from post_process.objective import total_cost, total_enclosure_cost
from post_process.solve_sa_continuous import hard_assign


def _population_cost(
    C_unary: Tensor,
    C_adj: Tensor,
    X_pop: Tensor,
    orig_dtype: torch.dtype,
    forbidden_enclosure_pairs: Optional[list[tuple[int, int]]] = None,
    C_enclose: float = 1e6,
) -> Tensor:
    """Cost of every particle's hard-assigned labeling.

    :param C_unary: (N, W, H, D, L)
    :param C_adj:   (L, L)
    :param X_pop:   (N, P, W, H, D, L) continuous logits
    :param forbidden_enclosure_pairs: list of (inner_layer_id, outer_layer_id)
                     pairs that must not fully enclose one another; see
                     `objective.enclosure_cost`. None disables the term.
    :param C_enclose: penalty weight applied per forbidden-enclosure violation
    :return:        (N, P) cost of each particle
    """
    N, P, W, H, D, L = X_pop.shape

    C_unary_pop = C_unary.unsqueeze(1).expand(N, P, W, H, D, L).reshape(N * P, W, H, D, L)
    Xh_pop = hard_assign(X_pop, orig_dtype).reshape(N * P, W, H, D, L)

    cost = total_cost(C_unary_pop, Xh_pop, C_adj)  # (N*P, 1)
    if forbidden_enclosure_pairs:
        labels_pop = Xh_pop.argmax(dim=-1)  # (N*P, W, H, D)
        cost = cost + total_enclosure_cost(labels_pop, forbidden_enclosure_pairs, C_enclose)
    return cost.reshape(N, P)


def _gather_best(X_pop: Tensor, idx: Tensor) -> Tensor:
    """Gather one particle per batch item out of the swarm.

    :param X_pop: (N, P, W, H, D, L)
    :param idx:   (N,) indices into the P dim
    :return:      (N, W, H, D, L)
    """
    N, P, W, H, D, L = X_pop.shape
    idx = idx.view(N, 1, 1, 1, 1, 1).expand(N, 1, W, H, D, L)
    return X_pop.gather(1, idx).squeeze(1)


def solve_ps(
    C_unary: Tensor,
    C_adj: Tensor,
    X_init: Optional[Tensor] = None,
    *,
    forbidden_enclosure_pairs: Optional[list[tuple[int, int]]] = None,
    C_enclose: float = 1e6,
    n_particles: int = 32,
    n_iter: int = 200,
    w_init: float = 0.9,
    w_final: float = 0.4,
    c1: float = 1.5,
    c2: float = 1.5,
    init_noise_scale: float = 1.0,
    v_init_scale: float = 0.1,
    v_max: Optional[float] = None,
    generator: Optional[torch.Generator] = None,
    validate_fn: Callable = None,
    verbose: bool = True,
) -> Tensor:
    """
    Particle swarm optimization for MRF labeling via continuous logit relaxation.

    Optimization variable: continuous logit tensor X of shape (N, W, H, D, L),
    one per particle. Constraint: exactly one label per voxel, enforced via
    argmax at each fitness evaluation — equivalent to softmax -> argmax.

    See module docstring for the swarm update loop (evaluate -> pbest ->
    gbest -> velocity -> position).

    :param C_unary:    (N, W, H, D, L) per-voxel-per-label unary costs
    :param C_adj:      (L, L) pairwise adjacency cost matrix
    :param X_init:     optional warm-start logits (N, W, H, D, L); defaults
                        to -C_unary. One particle is seeded with this value
                        unperturbed; the rest are noisy copies of it.
    :param forbidden_enclosure_pairs: list of (inner_layer_id, outer_layer_id)
                        pairs that must not fully enclose one another; see
                        `objective.enclosure_cost`. None disables the term.
    :param C_enclose:  penalty weight applied per forbidden-enclosure violation
    :param n_particles: swarm size per batch item
    :param n_iter:     number of PSO iterations
    :param w_init:     initial inertia weight (exploration)
    :param w_final:    final inertia weight (exploitation), linearly
                        annealed from `w_init` over `n_iter` iterations
    :param c1:         cognitive coefficient (pull toward personal best)
    :param c2:         social coefficient (pull toward global best)
    :param init_noise_scale: std of Gaussian noise used to diversify the
                        initial swarm around the seed logits
    :param v_init_scale: initial velocities are drawn from U(-v_init_scale, v_init_scale)
    :param v_max:      optional velocity clamp magnitude; None disables clamping
    :param generator:  torch Generator for reproducibility
    :param validate_fn: optional callback(labels) -> printed each iteration when verbose
    :param verbose:    print progress per iteration
    :return:           (N, W, H, D, L) one-hot label assignment
    """
    device = C_unary.device
    orig_dtype = C_unary.dtype
    N, W, H, D, L = C_unary.shape
    P = n_particles

    C_unary64 = C_unary.to(torch.float64)
    C_adj64 = C_adj.to(dtype=torch.float64, device=device)

    seed = -C_unary64 if X_init is None else X_init.to(torch.float64)  # (N, W, H, D, L)

    # Swarm init: particle 0 keeps the unperturbed seed (elitist start),
    # the rest are Gaussian-perturbed copies for diversity.
    X = seed.unsqueeze(1).expand(N, P, W, H, D, L).clone()  # (N, P, W, H, D, L)
    if P > 1:
        noise = torch.randn(X[:, 1:].shape, dtype=torch.float64, device=device, generator=generator)
        X[:, 1:] = X[:, 1:] + init_noise_scale * noise

    V = torch.empty_like(X).uniform_(-v_init_scale, v_init_scale, generator=generator)

    cost = _population_cost(C_unary64, C_adj64, X, orig_dtype, forbidden_enclosure_pairs, C_enclose)  # (N, P)

    pbest_X = X.clone()
    pbest_cost = cost.clone()

    gbest_idx = pbest_cost.argmin(dim=1)  # (N,)
    gbest_X = _gather_best(pbest_X, gbest_idx)  # (N, W, H, D, L)
    gbest_cost = pbest_cost.gather(1, gbest_idx.unsqueeze(1))  # (N, 1)

    best = {'iter': 0, 'X': gbest_X, 'cost': gbest_cost}

    for i in range(n_iter):
        w = w_init + (w_final - w_init) * (i / max(n_iter - 1, 1))

        r1 = torch.rand(X.shape, dtype=torch.float64, device=device, generator=generator)
        r2 = torch.rand(X.shape, dtype=torch.float64, device=device, generator=generator)

        V = (
            w * V
            + c1 * r1 * (pbest_X - X)
            + c2 * r2 * (gbest_X.unsqueeze(1) - X)
        )
        if v_max is not None:
            V = V.clamp(-v_max, v_max)

        X = X + V

        cost = _population_cost(C_unary64, C_adj64, X, orig_dtype, forbidden_enclosure_pairs, C_enclose)  # (N, P)

        improved = cost < pbest_cost  # (N, P)
        pbest_X = torch.where(improved.view(N, P, 1, 1, 1, 1), X, pbest_X)
        pbest_cost = torch.where(improved, cost, pbest_cost)

        gbest_idx = pbest_cost.argmin(dim=1)  # (N,)
        gbest_X = _gather_best(pbest_X, gbest_idx)  # (N, W, H, D, L)
        gbest_cost = pbest_cost.gather(1, gbest_idx.unsqueeze(1))  # (N, 1)

        gbest_improved = gbest_cost < best['cost']
        if gbest_improved.any():
            best['iter'] = i
            best['X'] = torch.where(gbest_improved.view(N, 1, 1, 1, 1), gbest_X, best['X'])
            best['cost'] = torch.where(gbest_improved, gbest_cost, best['cost'])

        if verbose:
            if validate_fn is not None:
                valid_result = validate_fn(hard_assign(best['X'], orig_dtype).argmax(dim=-1))
                print(f"Iter {i} | Best Cost: {best['cost'].mean():.4f} | Swarm Mean Cost: {cost.mean():.4f} | Valid Result: {valid_result}")
            else:
                print(f"Iter {i} | Best Cost: {best['cost'].mean():.4f} | Swarm Mean Cost: {cost.mean():.4f}")

    if verbose:
        print(f"Best Iter: {best['iter']} | Cost: {best['cost']}")

    return hard_assign(best['X'], orig_dtype)